# Generated by Django 5.1.5 on 2025-02-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dummymodel_remove_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(blank=True, default='profileImages/default.jpg', upload_to='profileImage/'),
        ),
    ]
