# Generated by Django 5.1.5 on 2025-02-06 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_delete_participant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvp_users',
            field=models.ManyToManyField(related_name='rsvped_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
